source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ForecastIOClient_Example', :exclusive => true do
  pod "ForecastIOClient", :path => "../"
end

target 'ForecastIOClient_Tests', :exclusive => true do
  pod "ForecastIOClient", :path => "../"

  
end
