source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ForecastIOClient_Example' do
  pod "ForecastIOClient", :path => "../"
end

target 'ForecastIOClient_Tests' do
  pod "ForecastIOClient", :path => "../"
  pod "Nimble" 
end
