source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ForecastIOClient_Example', :exclusive => true do
  pod "ForecastIOClient", :path => "../"
end

target 'ForecastIOClient_Tests', :exclusive => true do
  pod "ForecastIOClient", :path => "../"
  pod "Nimble", "2.0.0-rc.3" 
end
